[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "c1ad9b80bd5f3c0d61ad93d212880035cbf4f9d9"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2b391581ca6bd75b9a3d24f77bd72d0ef139957f4bed1683f7602df4dfeb3189"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "35a73e6d32bd8c180b908803e6cc8a108469a251"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "061ae261dd828ed7dd66ae02c9438445f1635430c920a8433e39a296c44aa27e"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "eed4536327d245dc88c60bcaa02a17b49afe7e69"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2f573ea32442784635fb0b5c7c9e8bd6bec0d0496302cdb19ac436562febd850"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "e074f4acf519cff707161057cdbd7fc963f7ebf1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "d81c63c1af9ff81a43f0c7328c733225bf2e5fa8115573ddb6f7855f0dcc4408"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "ab05a46ffa1788a56e85a81ed30d11176bc80b1e"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "7f26fd0df51b581d7c7acabeb73efd255fda2af288853815d4e0181aa0d5eb59"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "709c18e3345630a94a1a8cb7e372ad3f59cf6370"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "cb94ce4e698aaa36b072d57026c10f77c33f000b2fb5f98cb8e3da155346a190"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.4.29+0/UnoUtils.v2026.4.29.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4c4920433998a4dd8863e55fd3e5616473d7e29"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "f299356d8d34275a51b5121166fb779ced19348f420ccec64f14ba6d71cb8832"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.4.29+0/UnoUtils.v2026.4.29.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e7ebc81a6d8b163ec100fb12846484011fe51c3"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "84a461eea4ef10e1268a6255d860e997c1423cca1e7e258f5e5ed285fbfcd8f3"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.9.13+0/UnoUtils.v2026.9.13.aarch64-apple-darwin-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35c9b09b3c6f53fc6f555777aaeac615bea41c40"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "68f780ca1d6275019a3921316d322dc8ee34de43979055314222e0a6f918e983"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.9.13+0/UnoUtils.v2026.9.13.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e10e5348a93906c20546b49b5becbfa9d3ebc44"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "71049ca12c08876a8dc3bfd4739553a871371d1860f0503c6f680c65b59ad855"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.9.13+0/UnoUtils.v2026.9.13.x86_64-apple-darwin-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31c61973959e9f57d854a9063873b9cff6ab705b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "d767db354b7c2fe98d57c65c39f7733ce6b3b8f2713ab9418f600f072217ef6f"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.9.13+0/UnoUtils.v2026.9.13.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30f7156ab5614f5a2317f629015beae6f39c63ac"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "69f808f9fc1bb9d9ca6e9189353db6063af55b210e3b86e7b8a97884f43ad147"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.9.13+0/UnoUtils.v2026.9.13.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
