[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "c1ad9b80bd5f3c0d61ad93d212880035cbf4f9d9"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2b391581ca6bd75b9a3d24f77bd72d0ef139957f4bed1683f7602df4dfeb3189"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "35a73e6d32bd8c180b908803e6cc8a108469a251"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "061ae261dd828ed7dd66ae02c9438445f1635430c920a8433e39a296c44aa27e"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "eed4536327d245dc88c60bcaa02a17b49afe7e69"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2f573ea32442784635fb0b5c7c9e8bd6bec0d0496302cdb19ac436562febd850"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "e074f4acf519cff707161057cdbd7fc963f7ebf1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "d81c63c1af9ff81a43f0c7328c733225bf2e5fa8115573ddb6f7855f0dcc4408"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "ab05a46ffa1788a56e85a81ed30d11176bc80b1e"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "7f26fd0df51b581d7c7acabeb73efd255fda2af288853815d4e0181aa0d5eb59"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "709c18e3345630a94a1a8cb7e372ad3f59cf6370"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "cb94ce4e698aaa36b072d57026c10f77c33f000b2fb5f98cb8e3da155346a190"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.4.29+0/UnoUtils.v2026.4.29.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4c4920433998a4dd8863e55fd3e5616473d7e29"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "f299356d8d34275a51b5121166fb779ced19348f420ccec64f14ba6d71cb8832"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.4.29+0/UnoUtils.v2026.4.29.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebb3e7b1c367886d82d6167f69a31e6dfde18649"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "42187fbf13ca852d743b8905f11fb4c763521ac6aa32ea21294581adf455962d"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.7.1+0/UnoUtils.v2026.7.1.aarch64-apple-darwin-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2966a61d44b6d3839f17ea96147bb60edc21e516"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "c427c214e910ca728428771ff77d51862ba1f7e8c605d6108703780d328b86a7"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.7.1+0/UnoUtils.v2026.7.1.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb0c2f06ca7b8e85831ce8ccf06aa12fef4de2ce"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "40117acf160eaf13b4cadc09966bcbf369d7d7e6456e17e11a7fc5a6a0db7f78"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.7.1+0/UnoUtils.v2026.7.1.x86_64-apple-darwin-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05628d8fb612962127c542e8c109094a2b426a02"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "73d9aa978ba9a46d6d8382dd6c6a6023c9e41da2971f1fca4028b260465a7793"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.7.1+0/UnoUtils.v2026.7.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7787380675d5f6d365ed2420294aaaf3aeae8fe8"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "14e7679bf655f753ca14bdeefba29bc503868d4ca1e95728e4a3e14fabd4a0c2"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.7.1+0/UnoUtils.v2026.7.1.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
