[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "c1ad9b80bd5f3c0d61ad93d212880035cbf4f9d9"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2b391581ca6bd75b9a3d24f77bd72d0ef139957f4bed1683f7602df4dfeb3189"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "35a73e6d32bd8c180b908803e6cc8a108469a251"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "061ae261dd828ed7dd66ae02c9438445f1635430c920a8433e39a296c44aa27e"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "eed4536327d245dc88c60bcaa02a17b49afe7e69"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2f573ea32442784635fb0b5c7c9e8bd6bec0d0496302cdb19ac436562febd850"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "e074f4acf519cff707161057cdbd7fc963f7ebf1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "d81c63c1af9ff81a43f0c7328c733225bf2e5fa8115573ddb6f7855f0dcc4408"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "ab05a46ffa1788a56e85a81ed30d11176bc80b1e"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "7f26fd0df51b581d7c7acabeb73efd255fda2af288853815d4e0181aa0d5eb59"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0f6a5c33e574099b38a9d17b349f8c60d1dfd65"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "7d36bf4ade176a1b634833730da629a905d8b74b99e3aa228b651ad5df71de28"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.3.10+0/UnoUtils.v2026.3.10.aarch64-apple-darwin-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94798b64449dde91428faaf883d754731bfd13ab"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "1af37d626b7959ae31c1954fc475b14026381404a31aec79fcb76c0469aef291"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.3.10+0/UnoUtils.v2026.3.10.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2914140ec907b887a3265004e80b906621956dd0"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "ada144a5d4b46c238cbdb1556e1001dc83edadf76cb83cb1fe00db9761b8db4b"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.3.10+0/UnoUtils.v2026.3.10.x86_64-apple-darwin-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41795077ce8a17dc4a269163ee705c914cc20458"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "e3edc0d2c01d6d607aa86e7e982f043a9679da985055faedeb15876f9eac1d99"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.3.10+0/UnoUtils.v2026.3.10.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[UnoUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b83ef97a7ea6bc68525d770aada432bcdcf4b05"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "433b0fece46801bb14004b4700f980d57359ef5e33d4e538aec974a85b1dc87f"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.3.10+0/UnoUtils.v2026.3.10.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
