# Autogenerated wrapper script for UnoUtils_jll for x86_64-apple-darwin-libgfortran5
export libblas_a, libdmumps_a, libhighs_a, liblapack_a, libmetis_a, libmpiseq_a, libmumps_common_a, libpord_a

JLLWrappers.@generate_wrapper_header("UnoUtils")
JLLWrappers.@declare_file_product(libblas_a)
JLLWrappers.@declare_file_product(libdmumps_a)
JLLWrappers.@declare_file_product(libhighs_a)
JLLWrappers.@declare_file_product(liblapack_a)
JLLWrappers.@declare_file_product(libmetis_a)
JLLWrappers.@declare_file_product(libmpiseq_a)
JLLWrappers.@declare_file_product(libmumps_common_a)
JLLWrappers.@declare_file_product(libpord_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libblas_a,
        "lib/libblas.a",
    )

    JLLWrappers.@init_file_product(
        libdmumps_a,
        "lib/libdmumps.a",
    )

    JLLWrappers.@init_file_product(
        libhighs_a,
        "lib/libhighs.a",
    )

    JLLWrappers.@init_file_product(
        liblapack_a,
        "lib/liblapack.a",
    )

    JLLWrappers.@init_file_product(
        libmetis_a,
        "lib/libmetis.a",
    )

    JLLWrappers.@init_file_product(
        libmpiseq_a,
        "lib/libmpiseq.a",
    )

    JLLWrappers.@init_file_product(
        libmumps_common_a,
        "lib/libmumps_common.a",
    )

    JLLWrappers.@init_file_product(
        libpord_a,
        "lib/libpord.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
